### ISSUE TITLE
是否缺少ppadb文件？

### ISSUE THREAD

**Issue by Amovement** [AshenOneYe/WFHelper#105]
安装完依赖后，执行 `python .\main.py`
报错
`Traceback (most recent call last):
  File "F:\WFHelper-main\WFHelper-main\main.py", line 5, in <module>
    from wfhelper import WFHelperWrapper
  File "F:\WFHelper-main\WFHelper-main\wfhelper\__init__.py", line 1, in <module>
    from .WFHelperWrapper import WFHelperWrapper
  File "F:\WFHelper-main\WFHelper-main\wfhelper\WFHelperWrapper.py", line 4, in <module>
    from utils import Log, adbUtil
  File "F:\WFHelper-main\WFHelper-main\utils\__init__.py", line 1, in <module>
    from .ADBUtil import adbUtil
  File "F:\WFHelper-main\WFHelper-main\utils\ADBUtil.py", line 5, in <module>
    from ppadb.client import Client as AdbClient
ModuleNotFoundError: No module named 'ppadb'`

**Comment by ryan022730** [comment]
我也是这个问题

**Comment by AshenOneYe** [comment]
pip install pure-python-adb
