### ISSUE TITLE
cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by 847880028** [AshenOneYe/WFHelper#20]
```
2021/12/07 15:14:23 - INFO - 屏幕尺寸 : 1440x810
2021/12/07 15:14:25 - INFO - 配置文件初始化完成
2021/12/07 15:14:25 - INFO - 配置文件名称 : WF1440x810模拟器混铃铛
2021/12/07 15:14:25 - INFO - 配置文件作者 : 大A
2021/12/07 15:14:25 - INFO - 配置文件描述 : 这个配置用于世界弹射物语国服混铃铛，可以在1440x810分辨率的模拟器上运行
2021/12/07 15:14:25 - INFO - 服务器初始化完成
2021/12/07 15:14:25 - INFO - 开始自动脚本
2021/12/07 15:14:25 - INFO - server listening on 127.0.0.1:8765
2021/12/07 15:14:25 - INFO - server listening on [::1]:8765
Traceback (most recent call last):
  File "D:\WorldFlipper\WFHelper1\main.py", line 60, in <module>
    wfhelper.run(isDebug)
  File "D:\WorldFlipper\WFHelper1\WFHelper.py", line 85, in run
    self.loopDelay()
  File "D:\WorldFlipper\WFHelper1\WFHelper.py", line 59, in loopDelay
    a, b = self.config.loopDelay
TypeError: cannot unpack non-iterable int object
```
修改为 a = b = self.config.loopDelay后可以运行

**Comment by 847880028** [comment]
ui界面不同难度的boss勾选了会有什么效果呢

**Comment by AshenOneYe** [comment]
造成这个问题的原因是修改了loopdelay的类型为数组，但是我的配置文件忘记同步更新了，把config.json里的loopdelay改成[0,1]就行了，之后会修复这个问题；ui界面设计者不是我，应该需要配合配置文件使用，可以选择是否挑战某些boss，目前支持这个功能的应该只有那个蓝叠1280分辨率的配置文件

**Comment by Aetf** [comment]
https://github.com/Aetf/WFHelper/commit/5599aa6f55c38d76122a028b85647e95e672520b

本身代码逻辑是支持一个数或者一对数的，不过只判断了float没管int，改成检查list就行了。

**Comment by AshenOneYe** [comment]
> [Aetf@5599aa6](https://github.com/Aetf/WFHelper/commit/5599aa6f55c38d76122a028b85647e95e672520b)
> 
> 本身代码逻辑是支持一个数或者一对数的，不过只判断了float没管int，改成检查list就行了。

正解，因为近期又打算对config进行改动所以疏忽了那里的代码
